### ISSUE TITLE
PB to PowerServer

### ISSUE THREAD

**Issue by jojo5791** [OpenSourcePFCLibraries/2021#14]
Hi Sir or Madam,
I encountered Unsupported PowerServer errors that need your advice.  Please see below list of errors. What should i do to this? Thanks.

 ---------- Compiler: Unsupported Features for PowerServer Deployment   (8:23:24 PM)
pfcmain.pbl(d_printtree).36: Unsupported (PowerServer) C0228: Data.storage property in DataWindow (Suggestion: Add the WHERE clause to retrieve the data needed)
pfcmain.pbl(pfc_u_dw).pfc_u_dw.sqlpreview.41: Unsupported (PowerServer) C0237: previewinsert as the request argument of SQLPreview (Suggestion: Do not use it)
pfcmain.pbl(pfc_u_dw).pfc_u_dw.sqlpreview.42: Unsupported (PowerServer) C0237: previewupdate as the request argument of SQLPreview (Suggestion: Do not use it)
pfcmain.pbl(pfc_u_dw).pfc_u_dw.sqlpreview.43: Unsupported (PowerServer) C0237: previewdelete as the request argument of SQLPreview (Suggestion: Do not use it)
pfcapsrv.pbl(pfc_n_cst_conversion).pfc_n_cst_conversion.of_string.56: Unsupported (PowerServer) C0237: previewinsert as the request argument of SQLPreview (Suggestion: Do not use it)
pfcapsrv.pbl(pfc_n_cst_conversion).pfc_n_cst_conversion.of_string.58: Unsupported (PowerServer) C0237: previewdelete as the request argument of SQLPreview (Suggestion: Do not use it)
pfcapsrv.pbl(pfc_n_cst_conversion).pfc_n_cst_conversion.of_string.60: Unsupported (PowerServer) C0237: previewupdate as the request argument of SQLPreview (Suggestion: Do not use it)
pfcapsrv.pbl(pfc_n_cst_conversion).pfc_n_cst_conversion.of_sqlpreviewtype.63: Unsupported (PowerServer) C0237: previewinsert as the request argument of SQLPreview (Suggestion: Do not use it)
pfcapsrv.pbl(pfc_n_cst_conversion).pfc_n_cst_conversion.of_sqlpreviewtype.66: Unsupported (PowerServer) C0237: previewdelete as the request argument of SQLPreview (Suggestion: Do not use it)
pfcapsrv.pbl(pfc_n_cst_conversion).pfc_n_cst_conversion.of_sqlpreviewtype.69: Unsupported (PowerServer) C0237: previewupdate as the request argument of SQLPreview (Suggestion: Do not use it)
pfcapsrv.pbl(pfc_n_cst_conversion).pfc_n_cst_conversion.of_sqlpreviewfunction.65: Unsupported (PowerServer) C0237: previewfunctionreselectrow as the request argument of SQLPreview (Suggestion: Do not use it)
pfcapsrv.pbl(pfc_n_cst_conversion).pfc_n_cst_conversion.of_sqlpreviewfunction.71: Unsupported (PowerServer) C0237: previewfunctionupdate as the request argument of SQLPreview (Suggestion: Do not use it)
pfcapsrv.pbl(pfc_n_cst_conversion).pfc_n_cst_conversion.of_string.58: Unsupported (PowerServer) C0237: previewfunctionreselectrow as the request argument of SQLPreview (Suggestion: Do not use it)
pfcapsrv.pbl(pfc_n_cst_conversion).pfc_n_cst_conversion.of_string.64: Unsupported (PowerServer) C0237: previewfunctionupdate as the request argument of SQLPreview (Suggestion: Do not use it)
pfcmain.pbl(pfc_n_ds).pfc_n_ds.sqlpreview.53: Unsupported (PowerServer) C0237: previewinsert as the request argument of SQLPreview (Suggestion: Do not use it)
pfcmain.pbl(pfc_n_ds).pfc_n_ds.sqlpreview.54: Unsupported (PowerServer) C0237: previewupdate as the request argument of SQLPreview (Suggestion: Do not use it)
pfcmain.pbl(pfc_n_ds).pfc_n_ds.sqlpreview.55: Unsupported (PowerServer) C0237: previewdelete as the request argument of SQLPreview (Suggestion: Do not use it)
pfcmain.pbl(pfc_n_pl).pfc_n_pl.Forward Declarations.2: Unsupported (PowerServer) C0229: pipeline object (Suggestion: Create an application with the pipeline function and call it instead)
pfcmain.pbl(pfc_n_pl).pfc_n_pl.pfc_n_pl Class Declaration.1: Unsupported (PowerServer) C0229: pipeline object (Suggestion: Create an application with the pipeline function and call it instead)
pfcmain.pbl(pfc_n_pl).pfc_n_pl.Object Variable Declarations.1: Unsupported (PowerServer) C0230: pipeline object pfc_n_pl (Suggestion: Create an application with the pipeline function and call it instead)
pfemain.pbl(n_pl).n_pl.Forward Declarations.2: Unsupported (PowerServer) C0230: pipeline object pfc_n_pl (Suggestion: Create an application with the pipeline function and call it instead)
pfemain.pbl(n_pl).n_pl.n_pl Class Declaration.1: Unsupported (PowerServer) C0230: pipeline object pfc_n_pl (Suggestion: Create an application with the pipeline function and call it instead)
pfemain.pbl(n_pl).n_pl.Object Variable Declarations.1: Unsupported (PowerServer) C0230: pipeline object n_pl (Suggestion: Create an application with the pipeline function and call it instead)
pfcmain.pbl(pfc_n_tr).pfc_n_tr.of_copyto.50: Unsupported (PowerServer) C0231: sqlreturndata property in the transaction object (Suggestion: Do not use it)
pfcmain.pbl(pfc_n_tr).pfc_n_tr.of_copyto.50: Unsupported (PowerServer) C0231: sqlreturndata property in the transaction object (Suggestion: Do not use it)

**Comment by bruce-armstrong** [comment]
These are warnings, not errors.  For the vast majority of PFC applications, they affect area of code this isn’t used, and so the application is not affected.  You’ll need to look at your code to see if your application is affected

pfcmain.pbl(d_printtree).36: Unsupported (PowerServer) C0228: Data.storage property in DataWindow (Suggestion: Add the WHERE clause to retrieve the data needed)

Used to print from a treeview control.  If you don’t do printing from a treeview control, you won’t be affected.

pfcmain.pbl(pfc_u_dw).pfc_u_dw.sqlpreview.41: Unsupported (PowerServer) C0237: previewinsert as the request argument of SQLPreview (Suggestion: Do not use it)

There is a version of the u_dw of_update method that takes Boolean arguments for specifying if only certain updates ( insert, update or delete ) should be done.  That won’t function in a PowerServer app because the SQLPreview event won’t fire.  If you are not using that version of the of_update method, then you are not affected.

Also, since the SQLPreview only fires for Select, the SQL spy will only function for Select.  If you don’t use the SQL spy utility, you won’t be affected.

pfcapsrv.pbl(pfc_n_cst_conversion).pfc_n_cst_conversion.of_string.56: Unsupported (PowerServer) C0237: previewinsert as the request argument of SQLPreview (Suggestion: Do not use it)
pfcapsrv.pbl(pfc_n_cst_conversion).pfc_n_cst_conversion.of_string.58: Unsupported (PowerServer) C0237: previewdelete as the request argument of SQLPreview (Suggestion: Do not use it)
pfcapsrv.pbl(pfc_n_cst_conversion).pfc_n_cst_conversion.of_string.60: Unsupported (PowerServer) C0237: previewupdate as the request argument of SQLPreview (Suggestion: Do not use it)
pfcapsrv.pbl(pfc_n_cst_conversion).pfc_n_cst_conversion.of_sqlpreviewtype.63: Unsupported (PowerServer) C0237: previewinsert as the request argument of SQLPreview (Suggestion: Do not use it)
pfcapsrv.pbl(pfc_n_cst_conversion).pfc_n_cst_conversion.of_sqlpreviewtype.66: Unsupported (PowerServer) C0237: previewdelete as the request argument of SQLPreview (Suggestion: Do not use it)
pfcapsrv.pbl(pfc_n_cst_conversion).pfc_n_cst_conversion.of_sqlpreviewtype.69: Unsupported (PowerServer) C0237: previewupdate as the request argument of SQLPreview (Suggestion: Do not use it)
pfcapsrv.pbl(pfc_n_cst_conversion).pfc_n_cst_conversion.of_sqlpreviewfunction.65: Unsupported (PowerServer) C0237: previewfunctionreselectrow as the request argument of SQLPreview (Suggestion: Do not use it)
pfcapsrv.pbl(pfc_n_cst_conversion).pfc_n_cst_conversion.of_sqlpreviewfunction.71: Unsupported (PowerServer) C0237: previewfunctionupdate as the request argument of SQLPreview (Suggestion: Do not use it)
pfcapsrv.pbl(pfc_n_cst_conversion).pfc_n_cst_conversion.of_string.58: Unsupported (PowerServer) C0237: previewfunctionreselectrow as the request argument of SQLPreview (Suggestion: Do not use it)
pfcapsrv.pbl(pfc_n_cst_conversion).pfc_n_cst_conversion.of_string.64: Unsupported (PowerServer) C0237: previewfunctionupdate as the request argument of SQLPreview (Suggestion: Do not use it)

Not sure why you’re seeing these, I don’t.  It has to do with SQLPreview related types, but not with the SQLPreview itself.

pfcmain.pbl(pfc_n_ds).pfc_n_ds.sqlpreview.53: Unsupported (PowerServer) C0237: previewinsert as the request argument of SQLPreview (Suggestion: Do not use it)
pfcmain.pbl(pfc_n_ds).pfc_n_ds.sqlpreview.54: Unsupported (PowerServer) C0237: previewupdate as the request argument of SQLPreview (Suggestion: Do not use it)
pfcmain.pbl(pfc_n_ds).pfc_n_ds.sqlpreview.55: Unsupported (PowerServer) C0237: previewdelete as the request argument of SQLPreview (Suggestion: Do not use it)

Same as above for pfc_u_dw.  You’re only affected if you use the version of the of_update method that has the Boolean arguments indicating which updates are to be performed, or if you are using the SQL spy utility.

pfcmain.pbl(pfc_n_pl).pfc_n_pl.Forward Declarations.2: Unsupported (PowerServer) C0229: pipeline object (Suggestion: Create an application with the pipeline function and call it instead)
pfcmain.pbl(pfc_n_pl).pfc_n_pl.pfc_n_pl Class Declaration.1: Unsupported (PowerServer) C0229: pipeline object (Suggestion: Create an application with the pipeline function and call it instead)
pfcmain.pbl(pfc_n_pl).pfc_n_pl.Object Variable Declarations.1: Unsupported (PowerServer) C0230: pipeline object pfc_n_pl (Suggestion: Create an application with the pipeline function and call it instead)
pfemain.pbl(n_pl).n_pl.Forward Declarations.2: Unsupported (PowerServer) C0230: pipeline object pfc_n_pl (Suggestion: Create an application with the pipeline function and call it instead)
pfemain.pbl(n_pl).n_pl.n_pl Class Declaration.1: Unsupported (PowerServer) C0230: pipeline object pfc_n_pl (Suggestion: Create an application with the pipeline function and call it instead)
pfemain.pbl(n_pl).n_pl.Object Variable Declarations.1: Unsupported (PowerServer) C0230: pipeline object n_pl (Suggestion: Create an application with the pipeline function and call it instead)

I’m not getting these either.

pfcmain.pbl(pfc_n_tr).pfc_n_tr.of_copyto.50: Unsupported (PowerServer) C0231: sqlreturndata property in the transaction object (Suggestion: Do not use it)
pfcmain.pbl(pfc_n_tr).pfc_n_tr.of_copyto.50: Unsupported (PowerServer) C0231: sqlreturndata property in the transaction object (Suggestion: Do not use it)

This is in a function that copies all of the attributes of a transaction object onto another transaction object.  All that will happen here is that one attribute will be ignored.
